###### SETUP ANACONDA3 ######
#anaconda3
#export PATH="~/anaconda3/bin:$PATH"

# >>> conda initialize >>>
__conda_setup="$('/home/sholikinshino/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
# !! Contents within this block are managed by 'conda init' !!
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/sholikinshino/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/sholikinshino/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/sholikinshino/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
###### SETUP ANACONDA3 ######





###### EDITED BY ME ######
# auto mounting disk
#unset SUDO_UID SUDO_GID SUDO_USER

# Install Ruby Gems to ~/gems
#export GEM_HOME="$HOME/gems"
#export PATH="$HOME/gems/bin:$PATH"
#export PATH="$HOME/gems/bin:$PATH"

# Install golang
#export GOROOT=/usr/local/go
#export GOPATH=$HOME/go
#export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# Install jdk 14.0.1
#xport JAVA_HOME=/usr/local/jdk-14.0.1
#export PATH=$PATH:$JAVA_HOME/bin

# Install hadoop
#export HADOOP_HOME=/usr/local/hadoop/hadoop-2.10.0
#export PATH=$PATH:$HADOOP_HOME/bin

# Install spark
#export SPARK_HOME=/usr/local/spark
#export PATH=$PATH:$SPARK_HOME/bin
###### EDITED BY ME ######





###### SETUP DIRECTORY BY ME ######


# install own script
export SCRIPTS="$HOME/Scripts"
export PATH=$PATH:$SCRIPTS/bin
# install own script


# 1. cd scripts dir
export SCRIPTS=$HOME/Scripts/bin
alias scripts="cd $SCRIPTS"

# 2. cd downloads dir
export DOWNLOADS=$HOME/Downloads
alias downloads="cd $DOWNLOADS"

# 3. cd desktop dir
export DESKTOP=$HOME/Desktop
alias desktop="cd $DESKTOP"

# 4. cd music dir
export MUSIC=$HOME/Music
alias music="cd $MUSIC"

# 5. cd pictures dir
export PICTURES=$HOME/Pictures
alias pictures="cd $PICTURES"

# 6. cd templates dir
export TEMPLATES=$HOME/Templates
alias templates="cd $TEMPLATES"


### current working project ###
# 1. cd proyek_publikasi dir
export PROYEK_PUBLIKASI=$HOME/Desktop/Proyek_publikasi
alias proyek_publikasi="cd $PROYEK_PUBLIKASI"

## 1.a. cd proyek_plubikasi__amp dir
export PROYEK_PUBLIKASI__AMP=$HOME/Desktop/Proyek_publikasi/2_2019__AMP_Modelling
alias proyek_publikasi__amp="cd $PROYEK_PUBLIKASI__AMP"

### 1.a.i cd proyek_plubikasi__amp_broiler dir
export PROYEK_PUBLIKASI__AMP_BROILER=$HOME/Desktop/Proyek_publikasi/2_2019__AMP_Modelling/Database1_2019__Bioactive_peptide_broiler
alias proyek_publikasi__amp_broiler="cd $PROYEK_PUBLIKASI__AMP_BROILER"

### 1.a.ii cd proyek_plubikasi__amp_invitro dir
export PROYEK_PUBLIKASI__AMP_INVITRO=$HOME/Desktop/Proyek_publikasi/2_2019__AMP_Modelling/Database2_2019__Antimicrobial_peptide_invitro
alias proyek_publikasi__amp_invitro="cd $PROYEK_PUBLIKASI__AMP_INVITRO"

### 1.a.iii cd proyek_plubikasi__amp_babi dir
export PROYEK_PUBLIKASI__AMP_BABI=$HOME/Desktop/Proyek_publikasi/2_2019__AMP_Modelling/Database3_2020__Bioactive_peptide_babi
alias proyek_publikasi__amp_babi="cd $PROYEK_PUBLIKASI__AMP_BABI"

### 1.a.iv cd proyek_plubikasi__amp_review dir
export PROYEK_PUBLIKASI__AMP_REV=$HOME/Desktop/Proyek_publikasi/2_2019__AMP_Modelling/Database4_2020__Peptide_review
alias proyek_publikasi__amp_review="cd $PROYEK_PUBLIKASI__AMP_REV"

### 1.a.v cd proyek_plubikasi__amp_disertasi dir
export PROYEK_PUBLIKASI__AMP_DST=$HOME/Desktop/Proyek_publikasi/2_2019__AMP_Modelling/Database5_2020__Disertasi
alias proyek_publikasi__amp_disertasi="cd $PROYEK_PUBLIKASI__AMP_DST"

# 2. cd proyek_pmdsu dir
export PROYEK_PMDSU=$HOME/Desktop/Proyek_2018-2021_PMDSU-LPPM
alias proyek_pmdsu="cd $PROYEK_PMDSU"


### current website project ###
# 1. cd website project
export PROYEK_WEB=$HOME/Desktop/Proyek_web
alias proyek_web="cd $PROYEK_WEB"


### current skills update ###
# cd skill dir
export SKILL=$HOME/Desktop/Latihan_koding
alias skill="cd $SKILL"

# cd skill__bash dir
export SKILL__BASH=$HOME/Desktop/Latihan_koding/latihan_bash
alias skill__bash="cd $SKILL__BASH"

# cd skill__pentest dir
export SKILL__PENTEST=$HOME/Desktop/Latihan_koding/latihan_penetration
alias skill__pentest="cd $SKILL__PENTEST"

# cd skill__machinelearning dir
export SKILL__MACHINELEARNING=$HOME/Desktop/Latihan_koding/latihan_MachineLearning
alias skill__machinelearning="cd $SKILLS__MACHINELEARNING"

# cd skills_webapp dir
export SKILL__WEBAPP=$HOME/Desktop/Latihan_koding/latihan_django
alias skill__webapp="cd $SKILL__WEBAPP"
###### SETUP DIRECTORY BY ME ######





###### SETUP WEATHER ######
#weather(){ curl -s "http://api.wunderground.com/auto/wui/geo/ForecastXML/index.xml?query=${@:-<YOURZIPORLOCATION>}"|perl -ne '/<title>([^<]+)/&&printf "%s: ",$1;/<fcttext>([^<]+)/&&print $1,"\n"';}
###### SETUP WEATHER ######
